"""Added timestamp

Revision ID: b38f1863fc91
Revises: 37f4907b5503
Create Date: 2026-09-06 05:50:23.034271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38f1863fc91'
down_revision: Union[str, Sequence[str], None] = '37f4907b5503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('scrape_runs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('scrape_runs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'updated_at')
    op.drop_column('scrape_runs', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
